<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-98AE8SAQ" ignored="0" name="Retry Logic for MultipleTestCases" tests="16" failures="4" timestamp="2019-10-13T13:29:39 IST" time="0.097" errors="0">
  <testcase name="Test1" time="0.01" classname="retryLogic.myTestsTransformerLogic">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.001" classname="retryLogic.myTestsTransformerLogic">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.002" classname="retryLogic.myTestsTransformerLogic">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.002" classname="retryLogic.myTestsTransformerLogic">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at retryLogic.myTestsTransformerLogic.Test1(myTestsTransformerLogic.java:14)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
  <testcase name="Test2" time="0.001" classname="retryLogic.myTestsTransformerLogic">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.001" classname="retryLogic.myTestsTransformerLogic">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.001" classname="retryLogic.myTestsTransformerLogic">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.001" classname="retryLogic.myTestsTransformerLogic">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at retryLogic.myTestsTransformerLogic.Test2(myTestsTransformerLogic.java:20)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
  <testcase name="Test3" time="0.001" classname="retryLogic.myTestsTransformerLogic">
    <skipped/>
  </testcase> <!-- Test3 -->
  <testcase name="Test3" time="0.001" classname="retryLogic.myTestsTransformerLogic">
    <skipped/>
  </testcase> <!-- Test3 -->
  <testcase name="Test3" time="0.001" classname="retryLogic.myTestsTransformerLogic">
    <skipped/>
  </testcase> <!-- Test3 -->
  <testcase name="Test3" time="0.001" classname="retryLogic.myTestsTransformerLogic">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at retryLogic.myTestsTransformerLogic.Test3(myTestsTransformerLogic.java:26)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- Test3 -->
  <testcase name="Test4" time="0.001" classname="retryLogic.myTestsTransformerLogic">
    <skipped/>
  </testcase> <!-- Test4 -->
  <testcase name="Test4" time="0.002" classname="retryLogic.myTestsTransformerLogic">
    <skipped/>
  </testcase> <!-- Test4 -->
  <testcase name="Test4" time="0.001" classname="retryLogic.myTestsTransformerLogic">
    <skipped/>
  </testcase> <!-- Test4 -->
  <testcase name="Test4" time="0.001" classname="retryLogic.myTestsTransformerLogic">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at retryLogic.myTestsTransformerLogic.Test4(myTestsTransformerLogic.java:32)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- Test4 -->
</testsuite> <!-- Retry Logic for MultipleTestCases -->
